# Generated by Django 4.1.2 on 2024-01-23 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_contacto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
