# Generated by Django 4.1.2 on 2024-01-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_delete_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=20, null=True)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
