# Generated by Django 4.1.2 on 2024-01-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_alter_productos_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servilletas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('imagen', models.ImageField(upload_to='servilletas')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
