# Generated by Django 4.1.2 on 2024-01-29 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_servilletas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
        migrations.DeleteModel(
            name='productos',
        ),
        migrations.DeleteModel(
            name='Servilletas',
        ),
    ]
